-
    name: Copy kube cert to cvm
    hosts: seromcvm, selimcvm
    become: yes
    become_user: root
    tasks:
      - name: Ping Test
        ping:
      - name: Hostname name Display
        command: "hostname"
        register: logs
      - debug: var=logs.stdout
      - name: Copy cert to all cENM required cenm
        copy:
          src: "/home/cenmbuild/AUTO/kubeCert/"
          dest: "/etc/docker/certs.d/"
          owner: root
          group: root
          mode: 0644